### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ririko5834** [ffamilyfriendly/Thread-Watcher#11]
![image](https://user-images.githubusercontent.com/64729293/132380946-b78031b7-c57b-4bbf-9ff4-c0a6877bdb1b.png)

**Comment by ririko5834** [comment]
Using nodejs v16.6.1

**Comment by ririko5834** [comment]
@ffamilyfriendly

**Comment by ffamilyfriendly** [comment]
Sorry for rate reply! I cant seem to replicate this with the same version of node. Can you try running node with the flag `--input-type=module`? eg `node --input-type=module  .`

**Comment by ririko5834** [comment]
Still the same error 
![image](https://user-images.githubusercontent.com/64729293/132695364-59623dab-ee7f-40e9-8a5d-63da1ab17db2.png)

**Comment by ririko5834** [comment]
Solved by changing node-fetch version in package.json to 2.6.2. Why you dont have package.json in the repo?

**Comment by ffamilyfriendly** [comment]
> 
> 
> Solved by changing node-fetch version in package.json to 2.6.2. Why you dont have package.json in the repo?

Glad to hear you got it to work! No clue why there is no package.json I'll take a look
