### ISSUE TITLE
Use MongoDB database or add support for remote MySQL

### ISSUE THREAD

**Issue by ririko5834** [ffamilyfriendly/Thread-Watcher#30]
**Describe the feature you'd like**
It would be nice if this would use MongoDB database instead of .sqlite file. It's more stable, and you can get free database from MongoDB atlas.

**Additional context**
When this is not possible, add support to connect to remote MySQL database instead of using .sqlite file.

**Comment by ffamilyfriendly** [comment]
Thanks for the suggestion!
that's a pretty good idea! For the current scale of thread-watcher sqlite does the job however if the bot grows sqlite might cause some issues

I'll take a look at what needs to be done

**Comment by ririko5834** [comment]
You can use mongoose - https://www.npmjs.com/package/mongoose
