### ISSUE TITLE
Thread support tickets feature

### ISSUE THREAD

**Issue by ririko5834** [ffamilyfriendly/Thread-Watcher#31]
**Describe the feature you'd like**
Add command to make embed with button in some channel, then when users click on the button, a thread will be created for them. It could be good for support tickets and threads can see also other users, so for public support channels, it will be great to have it more organized.
Allow one user to have just one thread open at the time, threads should be named in `username-usertag` or `userid` format.

When a thread is opened by the bot, add there the user and send embed with a button to close it as first message. Then when staff clicks on this button, thread should be archived. Also owner of the thread (user) should be able to close it. when it's resolved.

Maybe there should be also option to add some pre-made questions that users can pick a question from menu or open a ticket.

Example:
![image](https://user-images.githubusercontent.com/64729293/150481466-50ab68e1-47fe-4fb5-a6d0-016be1d4f6ff.png)

Its from suggester support server - https://suggester.js.org/support

**Comment by ffamilyfriendly** [comment]
Hello and thanks for the feedback! The idea is really cool and I'm sure it would be helpful for a lot of servers. However, a core principle of thread-watcher is that it is basic and easy to use. Thread watcher really only exists to keep threads unarchived not to do anything else

I really do appreciate the idea but for the time being I'll have to pass on it

**Comment by ririko5834** [comment]
Can you make a different bot for this instead?

**Comment by ririko5834** [comment]
I think that server owners will appreciate it, it should have commands for adding pre-defined questions to menu, then command for removing pre-defined questions, for adding more buttons to message (like Resources button) that will reply with custom message and command to send the panel.

Maybe it could be made to support just for one server (selfhostable) so it will be easier for you to make it, that the pre defined questions, embed and others settings could be edited in config.js file.
