### ISSUE TITLE
More filter options for batch

### ISSUE THREAD

**Issue by ffamilyfriendly** [ffamilyfriendly/Thread-Watcher#36]
**Describe the feature you'd like**
more filter options like last message date, message count, archival status, and so on for threads.

**Comment by TheChilliPL** [comment]
It would be nice if you could filter out forum posts using tags
It'd make it a lot easier to manage forums if you could also add filters to `/auto`

**Comment by ffamilyfriendly** [comment]
Tags filtering and more filters are added to `/auto` in the V2 branch! I might add that filter to `/batch` after V2 has been deployed

**Comment by ffamilyfriendly** [comment]
This is how it'll look on the [V2](https://github.com/ffamilyfriendly/Thread-Watcher/tree/v2) branch which will be merged with main branch in a couple of days. If you are using the official instance of the bot you can expect to see these changes in action sometime this week
![example](https://i.imgur.com/B4R85Ad.png)

**Comment by TheChilliPL** [comment]
Would it be possible to make it watch posts *without* a specified tag?

**Comment by ffamilyfriendly** [comment]
not currently no but it might be something I add at a later stage
