### ISSUE TITLE
Private threads

### ISSUE THREAD

**Issue by ririko5834** [ffamilyfriendly/Thread-Watcher#6]
Make command to make "private thread", so when some user has joined the thread, automatically remove him.

**Comment by ririko5834** [comment]
Oh, I forgot that users are able to view thread messages without joining a thread. So it will be readonly thread, that users who are not invited to write there will be auto kicked.

Discord should add some better permissions system for threads, or atleast that you cant read thread messages when you dont join the thread

**Comment by ririko5834** [comment]
And make command to invite user to thread only usable by members with manage message perms in the thread channel. When user is added to thread using the command, bot should not kick him

**Comment by ffamilyfriendly** [comment]
That sounds like a good idea! however, I'm keen on keeping the bot as simple as possible. With that said this does sound related to what I want the bot to do so I might add this during (possibly) the weekend

**Comment by ffamilyfriendly** [comment]
while the idea is good I think it strays too far from what I designed the bot to do. Might look into this in the future
