### ISSUE TITLE
Unclose threads

### ISSUE THREAD

**Issue by ririko5834** [ffamilyfriendly/Thread-Watcher#66]
**Describe the feature you'd like**
Add option to unclose threads because Discord has removed archive threads option, I see just close/reopen thread when I go to thread options.
![image](https://user-images.githubusercontent.com/64729293/187036150-91cc1b05-3444-4e2f-9a95-810a086c7917.png)
In channel/thread settings there is this:

![image](https://user-images.githubusercontent.com/64729293/187036160-fa1cd64e-fcc4-488e-95c5-0a314f7c23ba.png)
![image](https://user-images.githubusercontent.com/64729293/187036163-3fa2a056-b8ca-46fe-a49c-90b2a0d1c0fc.png)

So thread without activity gets closed after selected time (can not set more than 1 week).

Thread watcher doesn't reopen threads that get auto closed after selected time.

**Additional context**

**Comment by ffamilyfriendly** [comment]
I'm pretty sure discord has just re-worded archival to "close threads". Bot seems to still work as expected. I've no clue as to why thread watched did not reopen the threads you tested on, i can finmd nothing in the logs unfortunetly

**Comment by ririko5834** [comment]
Does it normally work for you?

**Comment by ririko5834** [comment]
It didnt reopen it for me 
![image](https://user-images.githubusercontent.com/64729293/187069542-34f48a5e-a284-4246-bce3-d795d6f4c486.png)
