### ISSUE TITLE
Add Forum Channel Support

### ISSUE THREAD

**Issue by SmollClover** [ffamilyfriendly/Thread-Watcher#69]
**Describe the feature you'd like**
I'd love for the /auto command to be able to also watch Forum Channels so that Forum Posts also won't be archived like threads.

**Additional context**
As far as I can tell the Bot only supports Threads currently.

**Comment by ffamilyfriendly** [comment]
That is implemented in the [v2 branch](https://github.com/ffamilyfriendly/Thread-Watcher/tree/v2) that will be pushed to prod and merged with main in a matter of days

**Comment by matanshk** [comment]
There is estimated time for that?

**Comment by jestjest** [comment]
Looking forward to this change!

**Comment by ffamilyfriendly** [comment]
yeah this feature is being pushed tomorrow

**Comment by ffamilyfriendly** [comment]
Deployed!
