### ISSUE TITLE
Separation of configuration and code 

### ISSUE THREAD

**Issue by kmcbride3** [ffamilyfriendly/Thread-Watcher#75]
For discussion before I make any changes.

I propose that the configuration options be separated from the the codebase and instead pulled in on runtime - instead of being set via `config.ts`, they could instead be managed via a `.env` file or as runtime parameters, allowing for changes without rebuilding from source code.

Removing the requirement to customize & rename the example `_config.ts` as a dependency to successfully complete the build process enables prebuilt image creation & distribution, which could potentially be automated entirely through a CI/CD pipeline in the future.

This would also be more secure/reliable, in that the values wouldn't be directly imported (and thus could be sanitized/checked, and defaults provided) if the configuration is missing or wrong vs imported directly into the code. Added bonus, this would adhere to the [12 factor app principles for configuration](https://12factor.net/config).

**Comment by ffamilyfriendly** [comment]
will fix

**Comment by ffamilyfriendly** [comment]
Fixed in b5500ce
